export const UNKNOWN_VAR = 'UNKNOWN_VAR';
export const CIRCULAR_DEP = 'CIRCULAR_DEP';
export const DEPENDENCY_ERROR = 'DEPENDENCY_ERROR';
export const REDEFINE_VAR = 'REDEFINE_VAR';
export const MISSING_NAME = 'MISSING_NAME';
export const REPEAT_DEFINE = 'REPEAT_DEFINE';
export const WRAP_IN_NAME = 'WRAP_IN_NAME';
export const MISMATCHED_WRAP = 'MISMATCHED_WRAP';